# Generated by Django 5.2.8 on 2025-11-21 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_nom', models.CharField(max_length=40)),
                ('patient_prenom', models.CharField(max_length=30)),
                ('patient_genre', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=10)),
                ('patient_age', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('date_consultation', models.DateField(auto_now_add=True)),
                ('patient_adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('contenant', models.CharField(max_length=50)),
                ('duree_en_jours', models.PositiveIntegerField()),
                ('posologie', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='medico.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Urgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signes_vitaux', models.TextField()),
                ('remarque', models.TextField(blank=True, null=True)),
                ('date_signalement', models.DateTimeField(default=django.utils.timezone.now)),
                ('traitee', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.consultation')),
            ],
        ),
    ]
