# Generated by Django 5.2.6 on 2025-11-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('contenant', models.CharField(max_length=50)),
                ('duree_en_jours', models.PositiveIntegerField()),
                ('posologie', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='medico.consultation')),
            ],
        ),
    ]
