# Generated by Django 5.2.6 on 2025-11-07 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_traitement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signes_vitaux', models.TextField()),
                ('remarque', models.TextField(blank=True, null=True)),
                ('date_signalement', models.DateTimeField(default=django.utils.timezone.now)),
                ('traitee', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.consultation')),
            ],
        ),
    ]
